FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app/Gnoss.Web

RUN ls -1 /Gnoss.Web

COPY Gnoss.Web/Gnoss.Web.csproj ./Gnoss.Web
COPY Gnoss.Web/Gnoss.Commons ./Gnoss.Commons
RUN dotnet restore


COPY . ./
RUN dotnet publish Gnoss.Web/Gnoss.Web.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Gnoss.Web.dll"]