FROM nginx
RUN groupadd -g 2000 gnoss && useradd -u 2000 -g 2000 gnoss &&\
	mkdir -p /content &&\
	chown -R gnoss:gnoss /etc/nginx /content /var/cache &&\
	chmod -R 755 /etc/nginx /content &&\
	touch /var/run/nginx.pid && chown -R gnoss:gnoss /var/run/nginx.pid
USER gnoss
COPY Gnoss.Web.OpenCORE/Nginx/gnoss_services.conf.template /etc/nginx/conf.d/gnoss_services.conf.template
RUN cat /etc/nginx/conf.d/gnoss_services.conf.template
COPY Gnoss.Web.OpenCORE/Nginx/nginx.conf /etc/nginx/nginx.conf
