FROM nginx
RUN groupadd -g 1000 gnoss && useradd -u 1000 -g 1000 gnoss &&\
	mkdir -p /content &&\
	chown -R gnoss:gnoss /etc/nginx /content /var/cache &&\
	chmod -R 755 /etc/nginx /content &&\
	touch /var/run/nginx.pid && chown -R gnoss:gnoss /var/run/nginx.pid
USER gnoss
COPY Nginx/gnoss_services.conf.template /etc/nginx/conf.d/gnoss_services.conf.template
COPY Nginx/nginx.conf /etc/nginx/nginx.conf
