FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf &&\
    printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf

RUN apt-get update && apt-get install -y --no-install-recommends curl
# install libgdiplus for System.Drawing
RUN apt-get update && apt-get install -y --allow-unauthenticated libgdiplus libc6-dev

WORKDIR /app

COPY Gnoss.Web/*.csproj ./

RUN dotnet restore

# Install dotnet debug tools
RUN dotnet tool install --tool-path /tools dotnet-trace \
 && dotnet tool install --tool-path /tools dotnet-counters \
 && dotnet tool install --tool-path /tools dotnet-dump \
 && dotnet tool install --tool-path /tools dotnet-gcdump

COPY . ./

RUN echo $(date +%s) > Gnoss.Web/Config/version.txt

RUN dotnet publish Gnoss.Web/Gnoss.Web.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Copy dotnet-tools
WORKDIR /tools
COPY --from=build-env /tools .


RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf &&\
    printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf &&\
    printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf

RUN apt-get update && apt-get install -y --no-install-recommends curl
# install libgdiplus for System.Drawing
RUN apt-get update && apt-get install -y --allow-unauthenticated libgdiplus libc6-dev
WORKDIR /app
# RUN echo "Version    : $version \nProducto   : Web  \nFecha      : $(date +"%d/%m/%Y %H:%M:%S") \n" > wwwroot/versioninfo.txt
RUN groupadd -g 1000 gnoss && useradd -u 1000 -g 1000 gnoss &&\
    mkdir -p config logs trazas ViewsAdministracion &&\
	chown -R gnoss:gnoss config logs trazas ViewsAdministracion &&\
	chmod -R 777 config logs trazas ViewsAdministracion
USER gnoss
COPY --from=build-env /app/out .

COPY --from=build-env /app/Gnoss.Web.Open/Views/ Views/

COPY --from=build-env /app/Gnoss.Web.Enterprise/Views/ Views/

ARG version=latest

ENTRYPOINT ["dotnet", "Gnoss.Web.dll"]

