name: BuildWeb

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check out commons
      uses: actions/checkout@v2
      with:
        repository: equipognoss/Gnoss.Commons.OpenCORE
        token: ${{ secrets.MY_PAT }}
        path: ./Gnoss.Commons
        ref: develop
    - name: change folder
      run: |
        cd ..
        mv Gnoss.Web.OpenCORE/Gnoss.Commons Gnoss.Commons
        cd Gnoss.Web.OpenCORE
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
